### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars // ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by eforbes24** [denisecailab/minian#64]
Hey all!

The pipeline has been working great for single videos, however I am running into the following error when running it on a group of 20 (starting at smoothing signals, the entire terminal output of the pipeline is included here to show what steps are running successfully):

loading 20 videos in folder /work/miniscopepipeline/miniursi/videos/Animal_14/Day_4_FC
constructing chunks
creating parallel scheme
computing max projections
calculating local maximum
selecting seeds
computing peak-noise ratio
selecting seeds
performing KS test
computing distance
computing correlations
creating parallel schedule
computing ROIs
concatenating results
initializing backgrounds
estimating penalty parameter
computing subsetting matrix
fitting spatial matrix
removing empty units
updating background
background terms are empty
normalizing result
grouping overlaping units
computing trace
normalizing traces
smoothing signals
/home/eforbes/.local/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/work/miniscopepipeline/miniursi/minian/cnmf.py:60: RuntimeWarning: Mean of empty slice.
  return np.sqrt(np.exp(np.log(px_band + eps).mean()))
estimating AR coefficients
Traceback (most recent call last):
  File "ursi_pipeline.py", line 215, in <module>
    Y, A_spatial, b_spatial, C_spatial, f_spatial, sn_spatial, **param_first_temporal)
  File "/work/miniscopepipeline/miniursi/minian/cnmf.py", line 497, in update_temporal
    g = g.persist()
  File "/home/eforbes/.local/lib/python3.6/site-packages/xarray/core/dataarray.py", line 845, in persist
    ds = self._to_temp_dataset().persist(**kwargs)
  File "/home/eforbes/.local/lib/python3.6/site-packages/xarray/core/dataset.py", line 848, in persist
    return new._persist_inplace(**kwargs)
  File "/home/eforbes/.local/lib/python3.6/site-packages/xarray/core/dataset.py", line 822, in _persist_inplace
    evaluated_data = dask.persist(*lazy_data.values(), **kwargs)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/base.py", line 630, in persist
    results = schedule(dsk, keys, **kwargs)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/optimization.py", line 982, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/eforbes/.local/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/eforbes/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/eforbes/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2157, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/home/eforbes/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2198, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
  File "/work/miniscopepipeline/miniursi/minian/cnmf.py", line 648, in get_ar_coef
    g = lstsq(C_mat, cov[1:max_lag + 1])[0]
  File "/home/eforbes/.local/lib/python3.6/site-packages/scipy/linalg/basic.py", line 1157, in lstsq
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home/eforbes/.local/lib/python3.6/site-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
    a = toarray(a)
  File "/home/eforbes/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

At first I had thought this error was due to there being too many seeds generated, but following the advice of an earlier issue I had adjusted those parameters. As far as I am aware, the environment is also set up properly as defined in the environment.yml file. Any help would be fantastic!

Thanks so much

**Comment by wmau** [comment]
@phildong could this be due to removal of units happening during spatial update?

**Comment by eforbes24** [comment]
If it is any help, here are the parameters the pipeline is tuned to:

minian_path = "."
dpath = "./videos"
subset = dict(frame=slice(0,None))
subset_mc = None
interactive = True
output_size = 100

param_save_minian = {
    'dpath': dpath,
    'fname': 'pipeline_output',
    'backend': 'zarr',
    'meta_dict': dict(session=-1, animal=-2),
    'overwrite': True}

param_load_videos = {
    'pattern': '\.avi$',
    'dtype': np.uint8,
    'downsample': dict(frame=2,height=1,width=1),
    'downsample_strategy': 'subset'}

param_denoise = {
    'method': 'median',
    'ksize': 19}

param_background_removal = {
    'method': 'tophat',
    'wnd': 40}

subset_mc = None
param_estimate_shift = {
    'dim': 'frame',
    'max_sh': 20}

param_seeds_init = { 
    'wnd_size': 2000, 
    'method': 'rolling', 
    'stp_size': 1000, 
    'nchunk': 100, 
    'max_wnd': 19, 
    'diff_thres': 3}

param_pnr_refine = {
    'noise_freq': 0.45,
    'thres': 1,
    'med_wnd': None}

param_ks_refine = {
    'sig': 0.05}

param_seeds_merge = {
    'thres_dist': 5,
    'thres_corr': 0.7,
    'noise_freq': 0.45}

param_initialize = {
    'thres_corr': 0.8,
    'wnd': 15,
    'noise_freq': 0.45}

param_get_noise = {
    'noise_range': (0.1, 0.5),
    'noise_method': 'logmexp'}

param_first_spatial = {
    'dl_wnd': 19,
    'sparse_penal': 0.2,
    'update_background': True,
    'normalize': True,
    'zero_thres': 'eps'}

param_first_temporal = {
    'noise_freq': 0.1,
    'sparse_penal': 0.45,
    'p': 1,
    'add_lag': 20,
    'use_spatial': False,
    'jac_thres': 0.2,
    'zero_thres': 1e-8,
    'max_iters': 200,
    'use_smooth': True,
    'scs_fallback': False,
    'post_scal': True}

param_first_merge = {
    'thres_corr': 0.8}

param_second_spatial = {
    'dl_wnd': 19,
    'sparse_penal': 0.015,
    'update_background': True,
    'normalize': True,
    'zero_thres': 'eps'}

param_second_temporal = {
    'noise_freq': 0.1,
    'sparse_penal': 0.2,
    'p': 1,
    'add_lag': 20,
    'use_spatial': False,
    'jac_thres': 0.2,
    'zero_thres': 1e-8,
    'max_iters': 500,
    'use_smooth': True,
    'scs_fallback': False,
    'post_scal': True}

**Comment by wmau** [comment]
@eforbes24 Hi, are you still coming across this error or has it been resolved?

**Comment by phildong** [comment]
so it seems for some reason the `YrA` variable contains `NaN` values, which usually should not happen. A straight-forward workaround would be to compute it using `compute_trace`, then manually drop any NaN values with something like `YrA.dropna('frame', how='all)`. To figure out why this happens probably takes a bit more work, I'll give a check of all the input variables to `temporal_update`, none of them should contain `NaN`. This kind of nan-padding tend to happen when you load from previous results that has more labels on `unit_id` dimension than you currently have.

**Comment by phildong** [comment]
I assume this is no longer an issue in latest release. Feel free to reopen!
